test_task:
  container:
    image: ubuntu:18.04
  setup_script:
    - apt-get update
    - apt-get install -y python3 python3-pip build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev git
    - mkdir /src
    - cp app/requirements.txt /
    - cp -r app/src /
    - mkdir /config
    - cp config/app.conf.template /config/app.conf
    - pip3 install --requirement /requirements.txt
  test_script:
    - python3 /src/main.py
  binaries_artifacts:
    path: build/*
  always:
    junit_artifacts:
      path: "**/test-results/**.xml"
      type: text/xml
      format: junit