test_task:
  container:
    image: ubuntu:18.04
  setup_script:
    - apt-get update
    - apt-get install -y python3 python3-pip build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev git
    - pip3 install --requirement requirements.txt
  test_script:
    - src/python3 main.py
  environment:
  binaries_artifacts:
    path: build/*
  always:
    junit_artifacts:
      path: "**/test-results/**.xml"
      type: text/xml
      format: junit